name: Home Assitant Monerod
description: Home Assitant Monerod!
version: "1.0.0"
slug: homeassistantmonerod
init: false
arch:
  - armv7
  - aarch64
  - amd64
#map:
#  - share:rw
#image: "ghcr.io/home-assistant/{arch}-addon-example"