name: "Home Assistant Monero Miner"
description: "Home Assistant Monero Miner"
version: "1.0.1"
slug: "homeassistant_monerominer"
init: false
arch:
  - amd64
startup: application
options:
  maximum_amount_of_used_cores: 2
  wallet: "Enter wallet info here"
schema:
  maximum_amount_of_used_cores: int(1,16)